// <auto-generated />
namespace TransportDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Reservation_ClientID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reservation_ClientID));
        
        string IMigrationMetadata.Id
        {
            get { return "201706261755341_Reservation_ClientID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
